version: "3.9"

services:
  whoami:
    image: traefik/whoami
    command:
      # It tells whoami to start listening on 2001 instead of 80
      - --port 2001
      - --name test

networks:
  default:
    external: true
    name: public
