version: "3.9"

services:
  whoami:
    image: traefik/whoami
    # command:
    #   # It tells whoami to start listening on 2001 instead of 80
    #   - --port 2001
    #   - --name test
    ports:
      - "2001:80"
networks:
  default:
    external: true
    name: public
